# Generated by Django 5.0.2 on 2024-02-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdProducto', models.BigIntegerField()),
                ('FechaRegistro', models.DateField()),
                ('NomProducto', models.CharField(max_length=50)),
                ('NomCategoria', models.CharField(max_length=50)),
                ('cantidad', models.BigIntegerField()),
                ('FechaVencimiento', models.DateField()),
                ('Valorlibra', models.BigIntegerField()),
            ],
        ),
    ]
