# Generated by Django 5.0.2 on 2024-03-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idcompra', models.AutoField(db_column='IdCompra', primary_key=True, serialize=False)),
                ('fechaemision', models.DateField(db_column='FechaEmision')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=100)),
                ('valorproducto', models.IntegerField(db_column='ValorProducto')),
                ('valortotal', models.IntegerField(db_column='ValorTotal')),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(db_column='IdPedido', primary_key=True, serialize=False)),
                ('fechaemision', models.DateField(db_column='FechaEmision')),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('estado', models.CharField(db_column='Estado', max_length=50)),
                ('valortotal', models.IntegerField(db_column='ValorTotal')),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('fecharegistro', models.DateField(db_column='FechaRegistro')),
                ('nomproducto', models.CharField(db_column='NomProducto', max_length=50)),
                ('nomcategoria', models.CharField(db_column='NomCategoria', max_length=10)),
                ('cantidad', models.CharField(max_length=50)),
                ('fechavencimiento', models.DateField(db_column='FechaVencimiento')),
                ('valorlibra', models.IntegerField(db_column='Valorlibra')),
                ('foto', models.ImageField(null=True, upload_to='foto_productos')),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.IntegerField(db_column='IdProveedor', primary_key=True, serialize=False)),
                ('nomempresa', models.CharField(db_column='NomEmpresa', max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idrol', models.AutoField(db_column='IdRol', primary_key=True, serialize=False)),
                ('rolnombre', models.CharField(db_column='RolNombre', max_length=50)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(db_column='IdUsuario', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='Nombres', max_length=50)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=50)),
                ('fechanacimiento', models.DateField(db_column='FechaNacimiento')),
                ('direccion', models.CharField(db_column='Direccion', max_length=100)),
                ('telefono', models.CharField(db_column='Telefono', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('contrasena', models.CharField(db_column='Contrasena', max_length=50)),
                ('estado', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(db_column='IdVenta', primary_key=True, serialize=False)),
                ('fechaemision', models.DateField(db_column='FechaEmision')),
                ('idcliente', models.IntegerField(db_column='IdCliente')),
                ('producto', models.CharField(db_column='Producto', max_length=50)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('valorproducto', models.IntegerField(db_column='ValorProducto')),
                ('valortotal', models.IntegerField(db_column='ValorTotal')),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
