# Generated by Django 5.0.2 on 2024-03-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('iddetallecompra', models.AutoField(db_column='IdDetalleCompra', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('valorproducto', models.IntegerField(blank=True, db_column='ValorProducto', null=True)),
            ],
            options={
                'db_table': 'detalle_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('iddetallepedido', models.AutoField(db_column='IdDetallePedido', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('valorproducto', models.IntegerField(blank=True, db_column='ValorProducto', null=True)),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleventa',
            fields=[
                ('iddetalleventa', models.AutoField(db_column='IdDetalleVenta', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('valorproducto', models.IntegerField(blank=True, db_column='ValorProducto', null=True)),
            ],
            options={
                'db_table': 'detalleventa',
                'managed': False,
            },
        ),
    ]
